### ISSUE TITLE
I can not find jankson 2.0 anywhere.

### ISSUE THREAD

**Issue by obesevran** [CottonMC/Jankson-Fabric#4]
I have a mod "shulkercharm-1.1.2+1.15.2.jar" that say it requires jankson 2.0 i have "Jankson-1.0.0+j1.1.2.jar" and cannot find jankson 2.0 anywhere.

**Comment by falkreon** [comment]
jankson is generally JiJ'd (included) in projects that use it. Let me investigate what method was used in shulkercharm.

**Comment by falkreon** [comment]
update: shulker-charm, according to its source, ships the correct version of jankson in its release jar. You shouldn't have to worry about that dependency at all.

You may have issues if you try to mix 1.14 and 1.15 mods in the same environment - as the 1.14 mods will attempt to ship with and rely on 1.0.0, and fabric will pretty much give up on dependency resolution because the two versions are incompatible.
